// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0i1FtA2qZpGOkBsEEKfvfK4VBN7fupdk',
    appId: '1:60783317386:web:a43a6b0b0501da118f7873',
    messagingSenderId: '60783317386',
    projectId: 'easypos-4413a',
    authDomain: 'easypos-4413a.firebaseapp.com',
    storageBucket: 'easypos-4413a.appspot.com',
    measurementId: 'G-Z0D3QD4248',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN6jJaaeM9dAmmzmIIqENwdKh2TwvTyGQ',
    appId: '1:60783317386:android:0a54e8c1b7c7da188f7873',
    messagingSenderId: '60783317386',
    projectId: 'easypos-4413a',
    storageBucket: 'easypos-4413a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKJx0qgKwviPZhAGTnLLEBNVTKUEH1lTc',
    appId: '1:60783317386:ios:71e820f534eb12b58f7873',
    messagingSenderId: '60783317386',
    projectId: 'easypos-4413a',
    storageBucket: 'easypos-4413a.appspot.com',
    iosBundleId: 'com.example.candypos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKJx0qgKwviPZhAGTnLLEBNVTKUEH1lTc',
    appId: '1:60783317386:ios:71e820f534eb12b58f7873',
    messagingSenderId: '60783317386',
    projectId: 'easypos-4413a',
    storageBucket: 'easypos-4413a.appspot.com',
    iosBundleId: 'com.example.candypos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0i1FtA2qZpGOkBsEEKfvfK4VBN7fupdk',
    appId: '1:60783317386:web:9af0be18e273eb8c8f7873',
    messagingSenderId: '60783317386',
    projectId: 'easypos-4413a',
    authDomain: 'easypos-4413a.firebaseapp.com',
    storageBucket: 'easypos-4413a.appspot.com',
    measurementId: 'G-VEJB0THQ9J',
  );
}
